### ISSUE TITLE
General module questions

### ISSUE THREAD

**Issue by hansemannn** [facetec/titanium-module-zoom#2]
Hey there, Hans from Appcelerator here. I like this module and would like to improve it. Unfortunately the SDK itself (or it's .framework) does not seem to be open source as well. Is this planned for the future? It's quite hard to test code-improvements and drive community-contributions without that. Thanks!

P.S.: I saw you are using the Ti.SwiftSupport and Ti.DynamicLib module hook, cool! 

P.S. 2: Instead of mapping all the enum's manually, you can also use the `MAKE_SYSTEM_STR(nativeValue, MAPPED_VALUE)` macro :-).

**Comment by facetec** [comment]
Thanks Hans!

Would you mind reaching out to me at josh@facetec.com so we can discuss further?
